# Generated by Django 4.0.2 on 2022-04-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmap', '0003_blog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='date',
        ),
    ]
