# Generated by Django 4.0.2 on 2022-04-21 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmap', '0004_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
