# Generated by Django 4.0.2 on 2022-04-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nusmap', '0007_blog_short_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
