# Generated by Django 4.0.2 on 2022-04-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nusmap', '0008_delete_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sales',
            field=models.IntegerField(default=1),
        ),
    ]
